apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: un-acoperis-stage
  namespace: un-acoperis-stage
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "2"
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: utwo/war-acoperis:latest
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              php artisan config:cache &&
              php artisan view:cache &&
              php artisan migrate --seed --force &&
              exec /usr/sbin/apache2ctl -D FOREGROUND
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              value: "Un Acoperiș"
            - name: APP_ENV
              value: local
            - name: APP_DEBUG
              value: "true"
            - name: APP_URL
              value: "http://stage.unacoperis.ro"
            - name: LOG_CHANNEL
              value: stack
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: war-taskforce-mysql.c6oeti248oir.eu-west-1.rds.amazonaws.com
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: unacoperis-k8s
            - name: BROADCAST_DRIVER
              value: log
            - name: CACHE_DRIVER
              value: file
            - name: QUEUE_CONNECTION
              value: sync
            - name: SESSION_DRIVER
              value: database
            - name: SESSION_LIFETIME
              value: "120"
            - name: MAIL_MAILER
              value: smtp
            - name: MAIL_HOST
              value: email-smtp.eu-west-1.amazonaws.com
            - name: MAIL_HOST
              value: "587"
            - name: MAIL_ENCRYPTION
              value: tls
            - name: MAIL_FROM_NAME
              value: "Un Acoperiș"
            - name: MAIL_TO_HELP_ADDRESS
              value: noreply@unacoperis.ro
            - name: MAIL_FROM_ADDRESS
              value: noreply@unacoperis.ro
            - name: AWS_DEFAULT_REGION
              value: eu-west-1
            - name: SCOUT_DRIVER
              value: database
            - name: AWS_BUCKET
              value: un-acoperis-staging
            - name: AWS_CDN_URL
              value: http://un-acoperis-staging.s3-website-eu-west-1.amazonaws.com
            - name: AWS_PUBLIC_BUCKET
              value: un-acoperis-staging
            - name: AWS_PRIVATE_BUCKET
              value: un-acoperis-staging-private
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: un-acoperis-stage-secret
                  key: app_key
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: un-acoperis-stage-secret
                  key: database_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: un-acoperis-stage-secret
                  key: database_password
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: un-acoperis-stage-secret
                  key: mail_username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: un-acoperis-stage-secret
                  key: mail_password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: un-acoperis-stage-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: un-acoperis-stage-secret
                  key: aws_access_secret_key
            - name: NOCAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: un-acoperis-stage-secret
                  key: nocaptcha_secret
            - name: NOCAPTCHA_SITEKEY
              valueFrom:
                secretKeyRef:
                  name: un-acoperis-stage-secret
                  key: nocaptcha_sitekey
