apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: prod.unacoperis.ro
  namespace: un-acoperis
spec:
  ref:
    name: un-acoperis
    kind: Service
    apiVersion: serving.knative.dev/v1
